project:
  type: book

book:
  title: "Curated Siteswaps"
  author: "[John Zobolas](https://github.com/bblodfon)"
  date: last-modified
  description: "Siteswaps and Juggling Patterns"
  chapters:
    - index.qmd
    - siteswaps.qmd
    - misc.qmd
    - passing.qmd

format:
  html:
    page-layout: full