---
title: "Curated Siteswaps"
author: "[John Zobolas](https://github.com/bblodfon)"
date: "Last updated: `r format(Sys.time(), '%d %B, %Y')`"
description: "Siteswaps and Juggling Patterns"
url: 'https\://bblodfon.github.io/my-siteswaps/'
github-repo: "bblodfon/my-siteswaps"
site: bookdown::bookdown_site
editor_options: 
  markdown: 
    wrap: sentence
---

# Intro {-}

Knowledge acquired throughout years of practicing, playing over and over siteswaps, trying to find pleasant and/or aesthetic pattern characteristics through the siteswap numbering system.
This is a collection of what feels good for me, without taking the difficulty to the extreme levels (e.g. 7 balls+).

I also include specialized training regimes (again what worked for me best) and other miscellaneous stuff like mills mess and 3 ball patterns.

> *Push forward and hard*

John

------------------------------------------------------------------------

## Notes {-}

- *September 2022*: Changed to GitBook using [bookdown](https://bookdown.org/yihui/bookdown/).
- *November 2021*: I found a better name for my collection of siteswaps: **curated siteswaps**! This name better encapsulates my effort to find the best ones and what best exactly means. Still an ongoing process! Also finally the 5 ball siteswaps have become more stable :)
- *March 2021*: I have started realizing that using different colored objects to juggle is a major improvement over the unicolor culture that I was familiar with. The use of colors benefits your technique, it's more practical for learning new tricks, shows some hidden possibilities in your juggling exploiting a visual perspective, helps to build your own style and makes your mood better by adding an extra layer of diversity. So, I highly recommend it!
- *Somewhere in 2020*: After 10 years of Juggling, I understood this: it's all about the *form*, siteswaps especially. Also, **solidity of a siteswap/pattern** seems to hold a different meaning for each person but given 2 jugglers with different *solidity* everybody agrees to who is more solid! Lastly, 7 still is too much (balls) and I really don't find numbers above 7 worth pursuing anymore in siteswaps (form gets loose and unaesthetic). Found more meaning in 3 and 4 ball tricks, using imagination and of course club juggling that epitomizes that.
