# Preface {-}

Knowledge acquired throughout years of practicing, playing over and over with siteswaps, trying to find pleasant/aesthetic pattern characteristics using the siteswap notation system.
This is **a collection of what feels good for me**, without taking the difficulty to the extreme levels (e.g. 7+ balls).

I also include **specialized training regimes** (again what worked for me best) and other (miscellaneous) stuff like mills mess patterns, 3 ball tricks and **a lot of passing patterns** as well!

*John Zobolas*

## Notes {-}

- *July 2024*: Changed notation for passing patterns, I feel I am closing on a curated list for 2 and 3 person passing.
- *December 2023*: Changed to [Quarto](https://quarto.org/).
- *September 2022*: Changed to GitBook using [bookdown](https://bookdown.org/yihui/bookdown/).
- *November 2021*: I found a better name for my collection of siteswaps: **curated siteswaps**! This name better encapsulates my effort to find the best ones and what best exactly means. Still an ongoing process! Also finally the 5 ball siteswaps have become more stable :)
- *March 2021*: I have started realizing that using different colored objects to juggle is a major improvement over the unicolor culture that I was familiar with. The use of colors benefits your technique, it's more practical for learning new tricks, shows some hidden possibilities in your juggling exploiting a visual perspective, helps to build your own style and makes your mood better by adding an extra layer of diversity. So, I highly recommend it!
- *Somewhere in 2020*: After 10 years of Juggling, I understood this: it's all about the *form*, siteswaps especially. Also, **solidity of a siteswap/pattern** seems to hold a different meaning for each person but given 2 jugglers with different *solidity* everybody agrees to who is more solid! Lastly, 7 still is too much (balls) and I really don't find numbers above 7 worth pursuing anymore in siteswaps (form gets loose and unaesthetic). Found more meaning in 3 and 4 ball tricks, using imagination and of course club juggling that epitomizes that.
