# Miscellaneous {-}

## 3 Ball Tricks {-}

Various 3 ball tricks I have mastered throughout my juggling years :)

### Cascade Variations {-}

- Cross-arm Cascade
  - Reverse Cross-arm Cascade
  - Galerkin's Guitar - a Reverse Cross-arm Cascade with with the top hand doing a clawed elliptical chop - [video](https://www.instagram.com/p/CABUBdKgxwx/)
  - Frantic Cascade (continuous under the catches)
- Tennis
  - [2-colorable Tennis Variations in 52413 and 45141](https://www.instagram.com/p/B_mNs8_g81n/)
  - [2-colorable Tennis Variations in 45303 and 53403](https://www.instagram.com/p/CCTnR_agkrL/)
- **Penguin Cascade**
- Claw Cascade
  - (4x,2)\* with 2 as active claws!
- Chops
  - [Time Reverse Chops](https://www.instagram.com/p/CBD2byIAY7J/)
  - [Time Reverse Chop Var (NoSlowerDNA)](https://youtu.be/MFpF8N_rHOE?t=323)
  - [Time Reverse Chop + Claw-2x Box](https://www.instagram.com/p/CChJZCzgD6Y/) - 3rd and 4th patterns
  - [Time Reverse Chop + Broken Box](https://www.instagram.com/p/CClYuZFA0qx/) - 3-colorable (1 ball is caught continously under the arm, 1 stays in the center and 1 is being choped out!)
- 3-MM (MM => Mills Mess)
- 3-Pinball
- 3-bbb (blind behind the back) - [my attemps :)](https://www.instagram.com/p/CDHwAZHg7cl/)
- 333 (normal,rbxx,bxx)
  - claw catch the bxx ball
- 333 (normal, reverse/catch under the leg, throw under the leg)
- 3-Factory (normal,normal,carry)
- 3 continuous under-the-arm throw (Mike's Mess - 5D22)
  - Var: 52{wd}2 (wd = wrist-drop)
  - [Twisted Variation](https://youtu.be/QcLKwgk2pZ8?t=165)

### 423 Variations {-}

- 423 Tennis
- 423 MM, FMM (Takeouts)
- 4D2U3 MM with 2 active as *wrist drop*
- 423 with 2 active *goes outside* and is caught below other hand
- 423 claw (everything!)
  - Claw just the 3: [video](https://www.instagram.com/p/CChJZCzgD6Y/)
- 423 penguin variation (4 or 2 as penguin catches)
- 423 bxx (4 or 3 as bxx)
- [423 follow variation](https://youtu.be/bQvlinPcW8c?t=80): active 2 that circles the 3 (carry around), claw throw the 4
  - 423(follow var) + 3(carry)3 - [Relf's Factory](http://www.libraryofjuggling.com/Tricks/3balltricks/Relf'sFactory.html)!
- 423 **tornado**: 2 active in infinity motion
- [423 Weave (S)](http://www.libraryofjuggling.com/Tricks/3balltricks/Weave.html)
  - Var: 42423: [Orinoco flow](http://www.libraryofjuggling.com/Tricks/3balltricks/OrinocoFlow.html)
- 423 with 2 active drop, *catch under the leg* (nice)
- 423 (4 high throw and 3 overhead throw, catches 4)
- 423 overheads
- 423 with 4 as a pinball!
- 423 with 4 as a throw-and-stick-to-the-neck!

### Columns + Factory {-}

- 1up2up
- Cross-armed columns (sync Boston Mess)
- Infinity Columns, Reverse Infinity Columns
- Boxy-Columns
- Tennis-Columns
  - [1up2up-half-penguin-Tennis Var](https://www.instagram.com/p/CAQ2qu9ACmI/)
- [Fake Columns](https://youtu.be/U6wti1TvDpc?t=185)
  - Yo-Yo (+many variations on this, see a nice one [here](https://www.instagram.com/p/CM48A2Ln_s3/))
- [Factory](https://youtu.be/U6wti1TvDpc?t=360) (Symmetric version, 3-count)
- [Pendulum-Drop](https://youtu.be/U6wti1TvDpc?t=390) (Factory in 2-count, normal vs pendulum version)
- **Time-reversed Factory** (Symmetric version, 3-count, [Asymmetric version clip](https://youtu.be/U6wti1TvDpc?t=755))
- **Mess-Factory** or [Cross-armed Factory](https://youtu.be/U6wti1TvDpc?t=663)

### Box {-}

- Normal Box (4,2x)\*, Double Box
- [Swap Box](http://www.libraryofjuggling.com/Tricks/3balltricks/SwapBox.html) - (6,2x)(2x,2x)\*
- [Underarm Box](http://www.libraryofjuggling.com/Tricks/3balltricks/UnderarmBox.html)
- [Penman's Box](http://www.libraryofjuggling.com/Tricks/3balltricks/Penman'sBox.html)
  - [Penman's Pandemonium](http://www.libraryofjuggling.com/Tricks/3balltricks/Penman'sPandemonium.html) - 2x up!
- Slow Shuffle Box
- [Luke's Shuffle](http://www.libraryofjuggling.com/Tricks/3balltricks/Luke'sShuffle.html) (Box with slams)
- [Levels](http://www.libraryofjuggling.com/Tricks/3balltricks/Levels.html) (3-count, 2-count = 'pop-up' Box)
- [Burst Box/Symmetric Broken Box](http://www.libraryofjuggling.com/Tricks/3balltricks/BurstBox.html) (2 versions: under and over the arm catches)
- [Switched Columns Box](http://www.libraryofjuggling.com/Tricks/3balltricks/SwitchedBox.html)
- [Threaded Box](http://www.libraryofjuggling.com/Tricks/3balltricks/ThreadedBox.html) - continuous under the arm catches
- [Bizarre Box](http://www.libraryofjuggling.com/Tricks/3balltricks/BizarreBox.html) - fake 2x, bring it back!
- [Karas's Box](http://www.libraryofjuggling.com/Tricks/3balltricks/Karas'Box.html) - 2 x (fake 2x)!
- [Penguin Box](https://www.instagram.com/tv/B-PblMDAD9A)
- **Claw-2x** Box: 2nd pattern in the [video](https://www.instagram.com/p/CChJZCzgD6Y/)

### Others {-}

- [Boston Shuffle](http://www.libraryofjuggling.com/Tricks/3balltricks/BostonShuffle.html)
  - [Shuffle](http://www.libraryofjuggling.com/Tricks/3balltricks/Shuffle.html) - shower with slams!
  - [Burke's Slam](http://www.libraryofjuggling.com/Tricks/3balltricks/Burke'sSlam.html) - with takeouts!
  - [Tom's trick](http://www.libraryofjuggling.com/Tricks/3balltricks/Tom'sTrick.html) - Boston shuffle + chop
  - [Boston Shuffle + Bisector/Shapeshifter](https://www.instagram.com/tv/B_s_40TgB1f/)
  - **Boston Shuffle with 2x upwards** (changing trajectory, same as below)
  - [Boston Shuffle + Shapeshifter (upwards trajectory!)](https://youtu.be/FzFEtSLN5Cg?t=66)
  - [L-shower](https://www.instagram.com/p/CAHQAqbgm6y/) - **shuffle + broken box asymmetric**
  - [B.Shuffle + Broken Box (2x same ball always)](https://www.instagram.com/p/CChMYXAApe1/) - first trick
  - [Symmetric L-shower](https://youtu.be/bQvlinPcW8c?t=28) - 2-colorable, reach-under
  - [B.Shuffle + Broken Box extension](https://youtu.be/MFpF8N_rHOE?t=176) - like above + 1 extra throw to "give space"
  - [B.Shuffle + Burst Box](https://www.instagram.com/p/CChMYXAApe1/) - last trick (2x same ball always)
  - [Twisted Boston Shuffle](https://www.instagram.com/p/CBFzuH4A3xc/) - 1st pattern
  - [Peguinistic Boston Shuffle!](https://www.instagram.com/p/CDMwOVsAzEC/)
- 441/45141 Variations
  - [441 reverse + Burst box](https://youtu.be/J67qbuuZ85I) - 2-colorable!
  - [45141](https://www.instagram.com/p/CAVP8axglaG/), with 5 as an *under-the-arm* catch (async, sync + follow/S var) - 2-colorable!
  - [45141](https://youtu.be/svtqDpN6i78?t=361), with 5 as an *over-the-arm* catch - 2-colorable!
- [Hi there!](https://www.instagram.com/tv/B-9bbRbgvHc/) - a 52530 variation where you catch the 3 with a horizontal claw-catch + other tricks based on that catch
  - [52413 Hi There! Var](https://www.instagram.com/p/CAIhBlvg_Jn/)
- 23[43]423 ([43] as a 'traffic light' - all in a line, same colored balls)
- Rubinstein's Revenge (522+33)
  - Romeo's Revenge
  - [Relf's Rubensteins](http://www.libraryofjuggling.com/Tricks/3balltricks/Relf'sRubensteins.html) (combo of Romeo's + Rubi's)
  - Extended Rubistein (Rubi + kraken!)
- [Georgian Shuffle (Symmetric)](https://youtu.be/HgiMI46j0WY?t=307)
  - [Georgian Scuffle (Symmetric)](https://youtu.be/HgiMI46j0WY?t=491) - G.Shuffle + a little bit of kraken
- 531, 53142, 52413 *overheads*
- Penguin Tricks
  - [The confused Penguin](https://www.instagram.com/tv/B-FFADRAcWn/) - a 52530 variation where the first 5 is smaller than second, 53 feels like synced and you catch the 3 with a penguin-catch
  - [4pen41](https://www.instagram.com/p/B-PblMDAD9A) (*pen* = penguin-catch that throw)
  - [1up2up-half-penguin-Tennis Var](https://www.instagram.com/p/CAQ2qu9ACmI/)
  - 53pen1
  - [52512-pen](https://www.instagram.com/p/CCSAJ98AeGB/)
  - [Penguin Shower](https://www.instagram.com/p/CDHralFAZ4_/)
- [Catch-up!](https://www.instagram.com/p/CCSAyt7gWvg/)
- [Statue of Liberty](http://www.libraryofjuggling.com/Tricks/3balltricks/StatueofLiberty.html)
- [Hector's bisector](https://www.youtube.com/watch?v=BQC9Q2wKPsA)
  - [42333 Variations](https://youtu.be/BQC9Q2wKPsA?t=13) - both *inward* and *outward* 423's
  - [One-side bisector](https://youtu.be/BQC9Q2wKPsA?t=230)
  - [Twice per side bisector](https://youtu.be/BQC9Q2wKPsA?t=241)
  - [Taffy Puller](https://youtu.be/BQC9Q2wKPsA?t=299)
  - [Bursty Bisector/Parenthetical Perplexion](https://youtu.be/QyQ9pNvy4bY?t=24)
  - [Burke's Bender](https://www.instagram.com/p/B_TmCCQgUVs/) - a 423 bisector variation
- [The Shapeshifter](https://www.youtube.com/watch?v=Wrbzlipw0gA)
  - [2 balls shapeshift exercise](https://www.instagram.com/p/B_nbUe1gYBf/)
  - [441+33](https://www.instagram.com/p/B_N0FyTA2qx/) *shapeshift* the 2nd 4 (33 is done with the same hand)
  - [Broken Boston shifter!](https://youtu.be/svtqDpN6i78?t=46) - 2-colorable!

## 4 Ball Colored Patterns {-}

My favorite 4 ball colored siteswaps :)

The most interesting patterns (visually) have 2 or 3 colors.

### 2 colors {-}

#### 2+2 {-}

- **Base pattern is 552**. 
There are two chromaticities for the 55 throws: monochromatic <span style="color:red">55</span> and dichromatic <span style="color:red">5</span><span style="color:blue">5</span>.
We have 1 period per color when 55 is monochromatic and 4 periods when it is dichromatic - 2 as {<span style="color:blue">blue</span>,<span style="color:red">red</span>} and 2 as {<span style="color:red">red</span>,<span style="color:blue">blue</span>}.
So after 2 periods, there is a color order change in the 55 dichromaticity case.
- **Switch (monochromatic => dichromatic)**: <span style="color:red">55</span><span style="color:blue">2</span> - <span style="color:blue">53</span><span style="color:red">4</span> - <span style="color:red">5</span><span style="color:blue">5</span><span style="color:red">2</span> - see [video](https://www.instagram.com/p/CMiPdrdHxqX/)
  - The reverse transition (dichromatic => monochromatic) via a 534 must happen after the first <span style="color:blue">5</span><span style="color:red">5</span>2 or after the first <span style="color:red">5</span><span style="color:blue">5</span>2, but never during the change from {<span style="color:blue">blue</span>,<span style="color:red">red</span>} to {<span style="color:red">red</span>,<span style="color:blue">blue</span>}!
I shall say that this transition happens at 1st or 3rd period of the global dichromatic 552.
  - A siteswap that can be started from a dichromatic 552, **after the 1st or 3rd period**, and does not have transition throws, can be equivalently started from **each hand holding two balls of the same color**!
This means that you can go from a dichromatic 552 after the 1st or 3rd global period, to a fountain pattern with different color balls in each respective hand!
- Start with monochromatic 552: <span style="color:red">55</span><span style="color:blue">2</span> - <span style="color:blue">55</span><span style="color:red">613</span> - <span style="color:blue">63</span><span style="color:red">55</span><span style="color:blue">1</span> - see [video](https://www.instagram.com/p/CMfu9bJH5Rw/)
- Start with monochromatic 552: <span style="color:red">55</span><span style="color:blue">2</span> - <span style="color:blue">55</span> |<span style="color:red">714</span> - see [video (last sequence)](https://www.instagram.com/p/CMoxzEtgGrf/)
- Start with **1 color per hand**: <span style="color:blue">6</span><span style="color:red">4</span><span style="color:blue">2</span> - <span style="color:red">6</span><span style="color:blue">3</span><span style="color:red">6</span><span style="color:blue">41</span> - <span style="color:red">6</span><span style="color:blue">4</span><span style="color:red">6</span><span style="color:blue">13</span> - <span style="color:blue">5</span>|<span style="color:red">5</span><span style="color:blue">6</span><span style="color:red">1</span> - see [video 1 (full sequence)](https://www.instagram.com/p/CMkprhOncMA/) and [2 (part of sequence)](https://www.instagram.com/p/CMdAizKA-ws/)
- Start with **1 color per hand**: <span style="color:red">7</span><span style="color:blue">5</span><span style="color:red">2</span><span style="color:blue">5</span><span style="color:red">1</span> - see [video](https://www.instagram.com/p/CLJ5nRXgbnf/)
- Start with dichromatic 552 and switch after 2nd or 4th period (\*): <span style="color:blue">5</span>|<span style="color:red">74</span><span style="color:blue">1</span> - see [video](https://www.instagram.com/p/CMoxzEtgGrf/)
- (\*): <span style="color:blue">5</span>|<span style="color:red">66</span><span style="color:blue">1616</span><span style="color:blue">2</span> - see [video](https://www.instagram.com/p/CRbPnz0n4bj/)
- (\*): <span style="color:blue">7</span><span style="color:red">42</span><span style="color:blue">7</span><span style="color:red">242</span> - see [video](https://www.instagram.com/tv/CX9HXcaPgmb/)
- (\*): <span style="color:blue">5</span>|<span style="color:red">85</span><span style="color:blue">185</span>0<span style="color:red">1</span> - see [video](https://www.instagram.com/tv/CYBkkBfLpDf/)
- (\*): <span style="color:blue">8</span><span style="color:red">44</span><span style="color:blue">18</span><span style="color:red">414</span><span style="color:blue">8</span><span style="color:red">144</span><span style="color:blue">1</span> - see [video](https://www.instagram.com/p/CYFTlHcvCrh/)

(\*): These are equivalent to starting from 4 ball fountain with throws corresponding to colors as (<span style="color:blue">blue</span>,<span style="color:red">red</span>,<span style="color:red">red</span>,<span style="color:blue">blue</span>).
Note that the placement of the balls in your hands, so that the above throw sequence respects the coloring, forms a **crossing pattern**.

#### 3+1 {-}

With <span style="color:red">red</span> the one ball that does something completely different from the other 3!

- 555<span style="color:red">14</span> - 464<span style="color:red">5</span>1 - 63<span style="color:red">5</span>24 - <span style="color:red">5</span>3444 - 5<span style="color:red">3</span>4 - see [video](https://www.instagram.com/p/CIrfEPyAulN/)
- 555<span style="color:red">14</span> - 744<span style="color:red">14</span> - see [video](https://www.instagram.com/p/COD5XcyABKS/)
- 555<span style="color:red">14</span> - 5|68<span style="color:red">14</span>1 - see [video](https://www.instagram.com/p/CQLVL3wgPBr/)
- 555<span style="color:red">14</span> - 55|8<span style="color:red">14</span>61 - see [video](https://www.instagram.com/p/CQOMteAn32N/)
- 555<span style="color:red">14</span> - 5|68<span style="color:red">5</span>01 - see [video](https://www.instagram.com/p/CQqdt_Fntxx/)
- <span style="color:red">5</span>34 - 5|7<span style="color:red">5</span>161 - see [video](https://www.instagram.com/p/CP29iqZglHK/)
- 1-<span style="color:red">7</span> to 6<span style="color:red">7</span>16161 - see [video](https://www.instagram.com/p/CP8J6XKg3-e/)

### 3 colors {-}

#### 1+1+2 {-}

- <span style="color:green">4</span><span style="color:blue">5</span><span style="color:red">64</span><span style="color:green">1</span> - see [video](https://www.instagram.com/p/CIHBr8Fg9b3/)
- <span style="color:green">4</span><span style="color:red">64</span><span style="color:blue">5</span><span style="color:green">1</span> - see [video](https://www.instagram.com/p/CJzkuglgpZG/)
- <span style="color:red">12</span><span style="color:green">3</span><span style="color:red">4</span><span style="color:green">56</span><span style="color:blue">7</span> + the 2 above all in one sequence - see [video](https://www.instagram.com/p/CPsmUv_APlG/)
- <span style="color:blue">7</span><span style="color:red">36</span><span style="color:green">2</span><span style="color:red">5</span><span style="color:green">14</span> (start from fountain with throws corresponding to colors as <span style="color:blue">blue</span>,<span style="color:red">red</span>,<span style="color:red">red</span>,<span style="color:green">green</span>) - see [video](https://www.instagram.com/p/CRWTRx8H39D/)
- <span style="color:red">7</span><span style="color:blue">5</span><span style="color:red">3</span><span style="color:green">14</span> (start with 2 balls of the same color in one hand) - see [video](https://www.instagram.com/p/COv3pX7gYVt/)
- <span style="color:red">5</span>|<span style="color:blue">5</span><span style="color:red">8</span><span style="color:green">14</span><span style="color:red">2</span> (start with 2 balls of the same color in one hand) - see [video](https://www.instagram.com/p/COyGytNn7KT/)

### 4 colors {-}

- <span style="color:red">6</span><span style="color:green">3</span><span style="color:#CCCC00">7</span><span style="color:blue">2</span><span style="color:green">4</span><span style="color:blue">5</span><span style="color:red">1</span> - see [video](https://www.instagram.com/p/CQs7tqAH2ig/)

## Mills Mess {-}

Notation:

- R = Reverse (in time)
- F = Flipped
- Unless specified, each siteswap is done at all 3 positions: **U** (UP), **M** (MIDDLE), **D** (DOWN)

### 2 balls {-}

- [312 (3xMM with active 2)](https://www.instagram.com/tv/B9_3dENA-_b/)
  - 2 Var: wrist-up (MM, 3D), wrist-down (FMM, 3U)

### 3 balls {-}

#### Period 3 {-}

- [3 (MM,RMM,FMM,RFMM)](https://www.instagram.com/tv/B-ZqO9VgbhW/)
- [423](https://www.instagram.com/tv/B-cRXzog5pQ/), [441](https://www.instagram.com/tv/B-eqNqUg3ED/) (MM,FMM)
  - 4D23 - Burke's Barrage
  - **Twisted Burke's Barrage** - see [video (3rd pattern)](https://www.instagram.com/p/CA-3M4XAvN2/)
  - **Twisted Takeouts** - see [video (4th pattern)](https://www.instagram.com/p/CA-3M4XAvN2/)
- 531 (MM), 5U3D1 (FMM)
- [51 + Var](https://www.instagram.com/tv/B-Nakt2ACDU/)
- 4M-5D-0

#### Period 5 {-}

- [44403](https://www.instagram.com/tv/B-UaOtPAvYN/) (preparing for 4MM)
- [45141](https://www.instagram.com/tv/B-Nakt2ACDU/)
- [52512](https://www.instagram.com/tv/B-KpToKg5x_/) (baby juggling, the baby cries!)
- [53142](https://www.instagram.com/tv/B-KpToKg5x_/), [34512, 52413](https://www.instagram.com/tv/B-CcpDEA4pH/) (magic sequences)
- [53403](https://www.instagram.com/tv/B-UaOtPAvYN/) (nice!)
- [63141](https://www.instagram.com/p/CGuRqCQgO3H/), 2-colorable!
- [62313](https://www.instagram.com/p/CGnqpeLnMS0/), 3-colorable!

#### Other siteswaps {-}

- [531+441+423 (D)](https://www.instagram.com/tv/B-ibBaagZ_R/)
- [531+441+3](https://www.instagram.com/tv/B-ibBaagZ_R/)
- [5241+531](https://www.instagram.com/tv/B-ibBaagZ_R/) (favorite!!!)

#### Tricks {-}

- Windmill
  - Reverse Windmill
  - [Twisted Windmill](https://www.instagram.com/p/BewpyxGg_DP/)
  - [4233 Twisted Variation](https://www.instagram.com/p/CBBCgKrACeM/)
- Half-Mess (2 in each side, 3M3D3U + 3reverse)
  - **Claw Half-Mess**
- Boston Mess (2 directions)
  - [Cherry Picker](http://www.libraryofjuggling.com/Tricks/3balltricks/CherryPicker.html) - a claw half Boston Mess
- MM shower: 441+3M3D
- [Penguin MM](https://www.instagram.com/tv/B-PblMDAD9A/)
- FMM with *wrist-drop* on parallel with the middle throw
- 3M3U + 4M4U1 FMM (4 in each side)
- **Peruvian Mess**: 4D23D + 3U3M
- [Frostbite](https://youtu.be/UpTUpHQlMas)
  - [First 4 inside](https://youtu.be/nP0364EYuxc?t=7)
  - [441+3{M}3{U+claw}](https://youtu.be/nP0364EYuxc?t=28)
  - [Frostbite 531](https://youtu.be/cUfOLJbIMQ4?t=52) - can be combined with 33 as M,U+claw as above
  - [Twisted Frostbite](https://youtu.be/nP0364EYuxc?t=57)
  - [Frostbitten Bisector](https://youtu.be/nP0364EYuxc?t=96) - the hand that claws is the same one that bisects ([my video](https://www.instagram.com/p/CCTmkhwgV3Q/))
  - [Shapeshifted Frostbite](https://youtu.be/nP0364EYuxc?t=119)
  - [Frostbite + Galerkin's Guitar](https://www.instagram.com/p/CAZFMX_g6St/)
  - [Frostbiten Taffy Puller!](https://youtu.be/AMl03FZtLp8?t=38)
- [Orka's Mess](https://youtu.be/5hQoZG1b-Pg) - (4,4)(4x,0)(2,4)\*
- [Flo's Mess/Reach-over](https://youtu.be/qRvepXfoyZ0?t=183)
  - **Twisted Flo's Mess** - see [video (1st pattern)](https://www.instagram.com/p/CA-3M4XAvN2/)
- [Reach-under](https://youtu.be/qRvepXfoyZ0?t=263)
  - [Reach-under-penguin-catch](https://www.instagram.com/tv/B-PblMDAD9A/)
- **Mess Sync Var**: (6U,4D)(0,2x)(4D,2)\* (color-coded)
- [Kraken](https://youtu.be/K8rw8gxM2CA)
  - Var: Takeout (on the medium ball)
  - Var: Orbit (carry around)
  - Staken
- *NoSlowerDNA*-inspired tricks (Andrew Olson):
  - 4D23-MM + 5D1-like ([really smooth](https://youtu.be/cUfOLJbIMQ4?t=90)) - 2-colorable!
  - [(4x{U},2x)-3M3D (MM Var)](https://youtu.be/cUfOLJbIMQ4?t=141) - 2-colorable (the 4x{U} is the one-color ball, the 3D becomes the 3M)
  - 5-beat MM var (take the *Down* thrown ball and carry it to the other end)     
    - Var: 3D(and carried)3U + 4D4U1 MM ([really nice](https://youtu.be/QyQ9pNvy4bY?t=95))
  - [Monkey Mess - 44133](https://youtu.be/zJNVgO7RT10?t=29)
    - [Monkey Mess Variation](https://www.instagram.com/p/Bccc2KRAt9w/)
    - Twisted Monkey Mess! - see [video (2nd pattern)](https://www.instagram.com/p/CBFzuH4A3xc/)
  - [Moose Mess - 4413441 (frostbite variation)](https://youtu.be/zJNVgO7RT10?t=16)
- [Tonge Twister](https://youtu.be/TnRCag2ibHE?t=31) - a cross-arm mills mess variation!

### 4 balls {-}

- [4MM](https://www.instagram.com/tv/B_2a6xTAipu/)
- [4FMM](https://www.instagram.com/tv/CAAWkh9AJQK/)
  - 534-FMM (5{D}-[version](https://youtu.be/3O6OWj0O7W0?t=19))
  - 552-FMM (5{U}5{D}-[version](https://youtu.be/3O6OWj0O7W0))
- 4 Windmill, 4 Reverse Windmill
- [4 Ball Boston Mess](https://www.instagram.com/tv/CAkTvd2AVxK/)

#### Period 3 {-}

- 534 (difficulty ranking => 5{D} < 5{M} << 5{U})
- 552 (nice stuff!)
- 642 (6{M} and 6{D})
- 5{M}|5{D}61 (tricky, but nice)

#### Period 5 {-}

- **53444** (2-colorable, nice)
- **55514** (2-colorable, mmm)
- 46451 (amazing!)

### 5 balls {-}

- 5 MM is enough :)

## One Hand {-}

- 60 Inward (most basic)
- 60 Cascade, reverse cascade, columns
- 8040 (hi-low var)
- 80 (4 balls in one hand!)

## Sync {-}

### 3 balls {-}

- **312-sprung**: (6x,2x)(2x,2x)(4,2x)\*
- **330-sprung**: (6x,2x)(2x,6x)(0,2x)\*
- 3-sprung: (6x,2x)(2x,2x)\*

### 4 balls {-}

- Shower (6x,2x)
  - Hi-low Var: (8x,2x)(4x,2x)
  - b17131 (As sync, 3-levels var.)
- **3-sprung ball cascade**: (6x,4x)|(6x,2x)\*
- **423-sprung**: (6,4)|(8,2x)(2x,4)(6x,2x)
- **Box**: (6,2x)(6,2x)\*
  - **Multiplex Box**: ([64],2x)(2x,2)\*
  - **Stacked Box**: (6x,4)|(8,2x)(4,2x)\*
- 4-sprung 411: (8,4)(4,2x)(2x,4)\*

**Nice combinations**

- (6,4)(4x,2x)\*
- (6x,4x)(2x,4x)\*
- (6x,4)(4,2x)\*
- (6,4x)(2x,4)\*

### 5 balls {-}

- Shower (8x,2x)
- (6x,4)\*
  - (6x,4)(6x,4x)\*
- (6,4x)\* (**???**)
  - (8,2x)\* (4-sprung fountain, **???**)
  - (6,4x)(4x,6x)\*

**TO CHECK**

- (8,4)(4,8)(2x,4) (4-sprung 411)
- (4x,8x)(6x,4)(6x,2x)\*
- (6x,4)(8x,6)(4,2x)\* (looks amazing!!!)
- (8,6x)(6x,2x)(2x,6x)\* (Con(3,411)!!!)

### 6 balls {-}

**SOME "STANDARDS" TO CHECK IN THE FUTURE!!!**

- **(6,6)**
- (8,8)(4,4)
- **(8x,6)(4,6x)\* **
- (8,6)(4,8)(6,4)\*
- (8,4)\*
- (8x,4x)\*

## Multiplex {-}

### Duplexes {-}

#### 3 balls {-}

- [43]1421, 3|[43]0521 (5 in) - **color-coded**
- [43]5021 (5 out)
- **[54]1131, 3|[54]0141**
- 3[54]012

#### 4 balls {-}

- 4[42]2, 5[21][22] (feels like 501), 6[22]2[21][32]
- **3|[43]03[54]1** ([43] is under hand throw!)
- 3|[43]5521
- [43]23 (423-like)
  - 3 MM variations
  - 3[43]24[22] (**catch-up variation**, nice!)
- [43]14 (441-like)
  - [54]1622
  - 3|[54]6122
- 6[43]142, **642+1[43]**
- **3|[54]21**
- 3|[54]2333, 3|[54]2423
- 4[54]502, 3[54]512
- [54]1424, [54]1451
- 3|[64]2521, [64]1621, 3|[64]6121
- *Multiplex shower*: [75]15121

#### 5 balls {-}

- 1up4up
- 1up3up (the 1up crosses)
- [54][22]2 (normal duplex)
  - Reverse
  - MM with [54] as the 'down' throw
- 24[54] (Gattoplex)
- [33][33]3 (Cascade)
- [44][22]3 (423 Var)
- [44][44]14[22] (441 Var)
- [44]14 Var
- 25[62] (Martin's)

#### 6 balls {-}

- [33] (Duplexes - Cascade)
- [54][52]2 (552, multiplex version)
- 2up4up (sync, async)
- 3up (4,[44])\*

### Triplexes {-}

#### 5 balls {-}

[44x4x]-base:

- 22[43][22]3[345]5 (Denis Paumier)
- 24[22]3[345]
- 25[22]2[345]

#### 6 balls {-}

- ([444x],[22])(4x,[22])\* (building up for the 7 ball version)
- ~ [54]24[444x]262 (nice, complex one)

#### 7 balls {-}

- ([444x],2)\*

## 7 Balls Train {-}

A 7 Balls training program!
Warm-up with the 3 and 4 ball section, put more effort and time to the 5+ ball sections. 
You can also skip sections or mix them, e.g. start from the 5 ball section.
A good advice is to work yourself up to 7 **quickly** and do multiple short sessions/attempts on 7 during one practice (so not just once in the end when you are most tired).

### 3 Balls (warm-up) {-}

- 3-cascade: play with dwell time, high throws (722+), 3up

### 4 Balls (more warm up) {-}

- 741, 714, others...

**Core 7s**

- 71(shower), 5|7272712 (baby juggling)
- 56|7707070 (snake)
  - 2 Variations: start with 3 in one hand and 1 in the other. Either throw the 3 first or the 1
- 5|7770700 (3 and 1), 555|7077700 (1 and 3)

### 5 Balls {-}

**Stability + Core**

- 5-cascade (endurance!) + play with dwell time (high throws)
- 77722 (**3up**), 7777700 (**5up**)
- **744, 66|771**

**Extra**

- Half shower, 5-reverse cascade
- **5|77272** (snake - tough)
- **645**, (6x,4)\* (for fun!)

### 6 Balls {-}

**Core**

- 7777770 (six 7's)
- 77772 (four 7's)

**Extra**

- Half-shower: **75**
- **756**

### 7 balls {-}

- 7-cascade
