# Passing {-}

Passing patterns! Yay!

## 2 jugglers {-#2-person-passing}

Non-manipulation, non-moving patterns for 2 jugglers :)

### Notation

- "z" => zip (1)
- "f" => flip (2)
- "s" => self (3)
- "p" => single pass
- "d" => double pass
- "||" => straight pass
- "X" => cross pass
- "1|2" => start with 1 club on the left hand and 2 on the right
- "J1" => Juggler 1, "J2" => Juggler 2
- J1 does **straight passes** (||) and **starts first** (unless otherwise indicated)

### Zaps {-}

[Workshop collection](https://photos.app.goo.gl/ZQd3mDUCAUfTVaMD8)

- 522 (zap,zip,zip), 552 (zap,zip,zap)
- [556464](https://passist.org/siteswap/556464?jugglers=2) (zap,self,self vs zap,hold,hold)
- **zap intro** - <span style="color:blue">5</span>6464 (both: self,self,zap) - 5 is magic
- <span style="color:blue">5</span>6662 - 5 is magic
- [645](https://passist.org/siteswap/564?jugglers=2) (**Killer Bunny** - answer zap with self,zap)
  - [64555](https://passist.org/siteswap/55645?jugglers=2) (Funky magazine rack)
- 5 (1-count with zaps)
  - zaps (X) vs tomahawks (||)
  - zaps (||) vs bxxs (d,X)
- [7a224](https://passist.org/siteswap/7a224?jugglers=2) - single passes as zaps, and 5's as double selfs!
- 756 family:
  - 7<span style="color:blue">5</span>666 (2+3-count mix with zaps - 5 is magic)
  - **75666 vs why-not** (instead of pss{zap}s do psp41)
  - 756 (Baby Dragon)
  - 7<span style="color:blue">5</span>7<span style="color:blue">5</span>6 (2 magic 5s!)
- [85566](https://passist.org/siteswap/85566?jugglers=2)

### 3-5 clubs {-}

- [720](https://passist.org/siteswap/720?jugglers=2) - (501-like)
  - J1: (0|2, ||, p-wait-1)
  - J2: (0|1, X, 1-wait-p)
- 1-count (singles)
  - p31 (726)
  - d3131 ([96262](https://passist.org/siteswap/96622?jugglers=2))
- 41p31 (why-not)
- **Parsnip** ([ppzpz](https://passist.org/siteswap/77722?jugglers=2))

### 6 clubs {-}

**Sync passing**  

- 1,2,3,4-count
  - Pyramid variations
  - 1-count singles (p,X) vs bxxs (d,X)
  - 1-count singles (p,||) vs tomahawks (d,||)
  - Jim's 2-count - [77466](https://passist.org/siteswap/77466?jugglers=2)
- 3-count variations
  - 3d2 (early X-double)
  - **4d1 (early X-double)** - nice one, 441-ish
  - 42p, (4X)2(pX)
  - Jim's 3-count (77466666)
- pps, ppsps (**bookends**)
  - pps with 2 early doubles: ppdd13-pps

**Async (siteswap) passing**  

- **Why-not** - [77862](https://passist.org/siteswap/77862?jugglers=2)
  - J1: (2|2, ||, p3p41) or (1|2, ||, p41p3)
  - J2: (1|2, X, 41p3p)  or (1|2, X, p3p41)
  - Add an early double (Katia's idea): pd241 (p => ||, d => X) - [92478](https://passist.org/siteswap/92478?jugglers=2), has a stack
- **Maybe** - [78672](https://passist.org/siteswap/78672?jugglers=2)
  - J1: (1|2, ||, p314p)
  - J2: (1|2, X, 4pp31)
- **Mild Madness** - [7777266](https://passist.org/siteswap/7777266?jugglers=2)
  - J1: (1|2, ||, pp13pp3)
  - J2: (1|2, X, pp3pp13)
  - Nice to exchange {p,p} with {double,zap}
- **Heff-to-Flip** - [85746](https://passist.org/siteswap/85746?jugglers=2) - **???**
- [978822](https://passist.org/siteswap/978822?jugglers=2), 441's
  - J1: (1|2, X, d41)
  - J2: (1|2, X, p41)
- [979722](https://passist.org/siteswap/979722?jugglers=2), ddz vs ppz

**5-club vs 7-club patterns**  

- **5 club Why-not?** vs **5-count Popcorn**
  - J1: (1|2, ||, p3141)
  - J2: (1|2, X, 44p33)
- **Parsnip** vs **funky bookends**
  - J1: (1|2, ||, ppzpz)
  - J2: (1|2, X, p4pp3)
- **5 club 1-count** vs **French 3-count** - [784746](https://passist.org/siteswap/784746?jugglers=2)
  - J1: (1|2, ||, pff)
  - J2: (1|2, X, 4p3)

**Hijacking**  

- Why-not to (popcorn, 5-club why-not) => instead of p3p41, do p33+44
- Why-not to Maybe => instead of p3p+41, do pss+4pp31

**Siteswaps with single + double pass**  

- [972](https://passist.org/siteswap/972?jugglers=2) - has a stack
  - J1: (1|2, (X,||), d1p) - don't do the zip the first time!
  - J2: (1|2, (X,||), pd1)
- **Not likely** - [96672](https://passist.org/siteswap/96672?jugglers=2) - has a stack
  - J1: (1|2, (d => X), d313p)
  - J2: (1|2, (p => X), 3pd31)
- **Flip-to-Heff+stack** - [78456](https://passist.org/siteswap/78456?jugglers=2) - has stack
- **Odnom** - [7772964](https://passist.org/siteswap/7772964?jugglers=2) - has a stack
- **Maybe not** - [79662](https://passist.org/siteswap/79662?jugglers=2)
  - J1: (1|2, (d => X), p31d3)
  - J2: (1|2, (p => X), d3p31)
- **Israeli bicep curls** - [97842](https://passist.org/siteswap/97842?jugglers=2)

### 7 clubs {-}

- 1-count (singles)
- 2-count (sd or sp)
- 3-count
  - Async version (doubles): dss - (J1: ||, J2: X)
  - Sync version (**Techno**, singles): (RH p, LH 3)(RH 3)(LH p, RH 3)(LH 3) - (J1: ||), (J2: X)
- **Popcorn patterns**
  - **5-count** popcorn ([78686](https://passist.org/siteswap/78686?jugglers=2)) - can be 53 (triple,self) instead of 44
  - **6-count** popcorn with straight double passes (44d333)
- **French 3-count** - [786](https://passist.org/siteswap/786?jugglers=2)
  - J1: (2|2, ||, p34)
  - J2: (1|2, X, 4p3)
- **7 club 3-count** vs **French 3-count**
  - J1: (2|2, ||, p34)
  - J2: (1|2, ||, dss)
- **6 club 3-count** vs **Almost-French 3-count** - [786966](https://passist.org/siteswap/786966?jugglers=2)
  - J1: (2|2, ||, p33)
  - J2: (1|2, (d => ||), 4ds)
- **7 club 3-count** vs **stack** - [979962](https://passist.org/siteswap/979962?jugglers=2)
  - J1: (2|2, X, dd3)
  - J2: (1|2, (p => X), pd1)
  - Sync version: dd3 vs 3pd, with all doubles straight (||)
- **Funky Bookends** - [77786](https://passist.org/siteswap/77786?jugglers=2)
  - J1: (2|2, ||, pp3p4)
  - J2: (1|2, X, p4pp3)
- **Vitoria** - [7778686](https://passist.org/siteswap/7778686?jugglers=2)
  - J1: (2|2, ||, pp33p44)
  - J2: (1|2, X, p44pp33)
- [88892](https://passist.org/siteswap/88892?jugglers=2) (nice with 441, but difficult!)
  - J1: (1|2, X, 4414d)
  - J2: (2|2, ||, 4d441)
- **7-club why-not** - [9968926](https://passist.org/siteswap/9968926?jugglers=2)
  - J1: (2|2, X, d3d3d41)
  - J2: (1|2, ||, d41d3d3)
- **7-club maybe (1)** - [9969268](https://passist.org/siteswap/9969268?jugglers=2)
- [96677](https://passist.org/siteswap/96677?jugglers=2) (single + double passes, bookends variation)
- **Aspirin** - [7966786](https://passist.org/siteswap/7966786?jugglers=2)
  - J1: (2|2, (p => ||), p3p3d34)
  - J2: (1|2, (d => ||), d34p3p3)
- [979962](https://passist.org/siteswap/979962?jugglers=2)
  - J1: (2|2, X, dd3)
  - J2: (1|2, (p => X), pd1)
- **Double BANANA** - [966777777](https://passist.org/siteswap/966777777?jugglers=2)
  - J1: (2|2, (p => ||), d3ppp3ppp)
  - J2: (1|2, (d => ||), 3pppd3ppp)
- **5-count triples** - [b6666](https://passist.org/siteswap/b6666?jugglers=2)

### 8 clubs {-}

- [996](https://passist.org/siteswap/996?jugglers=2) - dds
- 2-count (ds, sync)
- [978888](https://passist.org/siteswap/978888?jugglers=2)
  - J1: (2|2, X, d44)
  - J2: (2|2, X, s44)
- [979968](https://passist.org/siteswap/979968?jugglers=2)
  - J1: (2|2, X, dd3)
  - J2: (2|2, (p => X), pd4)

### 6-handed siteswaps {-#6-handed-siteswaps}

The only online document on 6-handed siteswaps I know is [this one](https://passing.zone/wp-content/uploads/2021/02/3-Person6-handed-Siteswaps.pdf).
With regard to the hand-order, the aforementioned document mentions the *standard* (Ar-Bl-Cr-Al-Br-Cl) and the *staggered* (Ar-Al-Br-Bl-Cr-Cl) sequence, where A,B,C are the jugglers, and r = right hand, l = left hand.
In most patterns listed below, we have tried both the standard and a new hand order (Ar-Br-Cr-Al-Bl-Cl, let's call it *all-rights-all-lefts*), which made more sense to me compared to the one called *staggered*.
In most cases (but not all!), the patterns got more irregular (harder passes) and less interesting when using different hand orders from the *standard* one.
So, in all patterns listed below, we will use the *standard* hand order, unless otherwise specified.

#### 8 clubs {-}

- **Mayday zap** - [a37979999](https://passist.org/siteswap/a37979999?jugglers=3), [video](https://youtu.be/LXSHpPcaVTU), every juggler does something different
- Why-not with zaps (name?) - [8839c](https://passist.org/siteswap/8839c?jugglers=3)
  - Local is zap,3,zap,4,1

#### 9 clubs {-}

- **2-count mix** - [aa7999](https://passist.org/siteswap/aa7999?jugglers=3&hands=Ar-Br-Cr-Al-Bl-Cl)
  - Hand-order is *all-rights-all-lefts*
- **Gare du Zap** - [a8999](https://passist.org/siteswap/a8999?jugglers=3&hands=Ar-Br-Cr-Al-Bl-Cl), [video](https://passing.zone/gare-du-zap/) 
  - Hand-order is *all-rights-all-lefts*
- **Why-Not Triangle** - [aaac993bbbcc933](https://passist.org/siteswap/aaac993bbbcc933?jugglers=3), [video](https://passing.zone/whynot-triangle/)
  - Local siteswaps: 2 x a9bc3 and 1 x b9ac3

#### 10 clubs {-}

- [bbbcc9d3acacc93](https://passist.org/siteswap/bbbcc9d3acacc93?jugglers=3) - **TO-TRY**, 2 why-not feedees vs 1 feeder doing p4p44
- 2-count - [b9](https://passist.org/siteswap/b9?jugglers=3&hands=Ar-Bl-Cr-Al-Br-Cl)

#### 11 clubs {-}

- 2-count - [d9](https://passist.org/siteswap/d9?jugglers=3&hands=Ar-Bl-Cr-Al-Br-Cl)

#### 13 clubs {-}

- 2-count - [h9](https://passist.org/siteswap/h9?jugglers=3&hands=Ar-Bl-Cr-Al-Br-Cl)

## 3 jugglers {-#feeds}

Most patterns in this section are either *feeds* or *triangles*, i.e. static (non-moving) patterns for **3 jugglers**.
In feeding patterns, one person (the *feeder*) passes to the other two (the *feedees*), while the feedees don't pass to each other 
(so it is kinda like 1 vs 2).
In triangles, every juggler passes with everyone else.

An example of a nice moving pattern for 3 jugglers is **Bruno's Nightmare**.
I personally prefer the 3‑count version where a giant juggles 3 jugglers and the 2 feedees do 6‑count, and the feeder does 3‑count 
and then they change roles.

Useful notation:

- "F" => Feeder
- "LF" => Left-Feedee and "RF" => "Right-Feedee" refer to the two feedees/passers **as the feeder views them**
- "R" => starts right-handed, "L" => starts left-handed
- "||" => straight passes, "X" => cross passes

### 9 clubs {-}

- **Triangle sync counts** (2,3,4-count, pps, ppsps)
- **Gorilla: 1-count feeds two 2-counts**
  - F: (R, ||, 1-count) - first pass to LF
  - LF: (R, ||, 2-count)
  - RF: (L, ||, 2-count) - starts on 2nd beat
- **2-count feeds two 4-counts**
  - Variation: Runaround (changes feeder - base pattern for Scramble-V)
- **PPS feeds two 3-counts**
  - Variation: Runaround (the person who walks does a 4-count, the feeder does a 2-count with the same person that is not moving, the future feeder does sp (2-count) + psppspps...
- **1-count chocolate bar feed**
  - Feeder does 1-count, 2 straight passes in one feedee, 2 in the other
  - Feedees: ppss (one starts two beats later or with ss)
- **Dropback Line**
  - Dropback pass ⇒ (straight) double pass behind the shoulder.
  - A,B vs C: A ⇒ C, C ⇒ B, B (dropback) ⇒ A. A and C throw single passes.
- **Parsnip feeds 5-count popcorn and 6-club why-not**
  - F: (R, ||, ppzpz) - first pass to LF, two next to RF
  - LF: (R, X, 44p33)
    - Change to an 8-club pattern with LF: (R, X, 41p31) - starts with 2 clubs
  - RF: (R, X, p41p3)
- **1-count feast**
  - All jugglers do pps out-of-phase
  - All start **right-handed**
- **ppz feeds two french 3-counts**
  - F: (R, ||, ppz) - in,in,out,out
  - LF: (R, ||, 4p3)
  - RF: (R, ||, 34p)
- **ppzspps feeding two Jim's 3-counts**
  - Feeder: ||, feedees: X

### 10 clubs {-}

- **3-count triangle with doubles**
  - One juggler with 4 clubs, starts first with a pass
  - Crossing doubles for all
  - Passes go: A => B, B => C, C => A
  - A: pss, B: sps, C: ssp
- **Gorilla (singles)**
  - F: (L, 2|2, X, 1-count) - first pass to LF
  - LF: (R, ||, 2-count)
  - RF: (L, ||, 2-count)
- **2-count feeds two 4-counts with doubles**
  - Variation: Runaround (when the feeder changes - base pattern for Ambled-V)
- **6-club why-not feeds two 5-count popcorns**
  - F: (R, 2|2, ||, p3p41) - starts with LF
  - LF: (R, X, 44p33)
  - RF: (R, X, 3344p) or wait for feeder's pass and do: (R, X, 44p33)
- **6-club Maybe feeds two 5-count popcorns**
  - Same configuration as above pattern, RF waits 1 beat less time for feeder's pass
- **Funky bookends feeds 5-count popcorn and 6-club why-not** - COLLISIONS?
  - F: (R, 2|2, ||, pp3p4) - first pass to LF, two next to RF
  - LF: (R, X, 44p33)
  - RF: (R, X, p41p3)
- **3-count feeds two 6-count popcorns**
  - F: (L, 2|2, X, 3-count) - starts with LF
  - LF: (R, 1|2, ||, 44p333) - passes with right hand
  - RF: (R, 1|2, ||, 33344p) - passes with left hand
- **3-count feeds two french 3-counts**
  - F: (R, 2|2, ||, pps)
  - LF: (R, 1|2, ||, 4p3) - start exactly the same time as F, fast single pass
  - RF: (R, 1|2, X, 34p) - start 1 beat later than F, lofty single pass

### 11 clubs {-}

- **1-count feeds two 2-count with doubles**
  - Proposed name: Gorilla+
  - F: (R, 2|2, ||, d) - first pass to LF, second to RF
  - LF: (R, 1|2, ||, d3) - waits 1 beat
  - RF: (L, 2|2, ||, d3) - starts with F
- **2-count feeds two 4-count popcorns with doubles**
  - F: (R, 2|2, ||, ds) - first pass to LF, second to RF
  - LF: (L, 2|1, ||, 344d) or (R, 1|2, ||, 44d3) but waits 1 beat (better for some people)
  - RF: (L, 2|2, ||, 4d34) - starts with F
- **PPS feeds 3-count with doubles** (996 vs 2x966)
  - F: (R, 3|2, dds) - out,out,in,in, starts with **5 clubs**
  - LF: (R, 1|2, X, dss)
  - RF: (R, 1|2, X, sds)

## 4 jugglers

Unless otherwise specified, each juggler has 3 clubs and the patterns are for 4 x 3 = 12 clubs in total.

- **4-person feeds**
  - Square positioning: top ⇒ {A,C}, bottom ⇒ {B,D}.
  - Two jugglers are feeding (B,C), two are feedees (A,D).
  - Feeders: 2-count, Feedees: 4-count.
  - Feeders: pps, Feedees: 3-count.
  - Feeders: 1-count, Feedees: 2-count or pps or chocolate bar (ppss)
- **4-person feasts**
  - Square positioning as in the feeds above.
  - Every juggler passes to every other juggler in turn, including themselves!
  - Works with 1,2,3,4-counts!
- **Weaver**
  - Feeder: 2‑count and feeds like a windshield 3 people.
  - Feedees: 6‑count and moving as a 3‑people cascade.
  - Static weaver: feedees do not move!
- **Y** (2,3,4‑count)
- **3- vs 2‑count**
  - Cross(+) positioning: each 2‑person group forms a line, and the two lines are perpendicular.
  - 2 people do 2‑count, 2 people do 3‑count.
  - Right‑hand start for all.
  - 2‑count person: left, middle, middle, right, middle, middle, left, ...
  - 3‑count person: right, middle, left, middle, right, ...
- **Shooting star (9 clubs, 4‑count)**
  - 5 people, pentagram positioning: A ⇒ B ⇒ C ⇒ D ⇒ E (think A is top in a diagram and the arrow shows who is “right‑next‑to” the previous person).
  - A, C and E start with 3 clubs (1|2), B starts with no clubs, D is phantom.
  - Right‑hand start for all.
  - Pass to the person two to your right, i.e. A ⇒ C, C ⇒ E, E ⇒ B.
  - When A is out of clubs, runs to point D (where he/she was expecting passes from).
- **Shooting star (11 clubs, 4‑count)**
  - Same as above, but faster.
  - B has 2 clubs now.
  - A starts the run immediately after the first pass, then C moves (after one 4‑count), then E (after two 4‑counts), then B (after three 4‑counts).
- **Dropback Line**
  - Dropback pass ⇒ (straight) double pass behind the shoulder.
  - Line positioning: A,B vs C,D. B and C can be standing next to each other, kinda perpendicular to the line created by A and D (this makes passing easier).
  - Passes: A ⇒ C, C (dropback) ⇒ D, D ⇒ B, B (dropback) ⇒ A.
  - Also this positioning works (bit harder): A,B,C vs D. Passes: A ⇒ D, D ⇒ C, C (dropback) ⇒ B, B (dropback) ⇒ A.
- **Why-not box**
  - In a square positioning, everyone passes 6-club *Why not?* with two other people.
  - B and D start at the same time and throw straight passes.
  - B ⇒ A,4,1,C,3.
  - D starts with four clubs and does C,3,A,4,1.
  - A and C start half a beat later and throw crossing passes.
  - A starts with two clubs and does 4,1,B,3,D.
  - C does B,3,D,4,1.
- **Why‑not feed**
  - Feeders do why‑not.
  - People at the ends do 5‑count popcorn or 5‑club why‑not.
  - Two lines of people: one line starts, everyone there has 4 clubs; the other line responds, why‑not jugglers have 2 clubs, 5‑count popcorn start with 3 clubs.
  - If the starting side does *straight passes*, everyone can start right‑handed.
  - Can be more than 4 people!
- **8-handed siteswaps**
  - [3-count friction](https://youtu.be/g4q6-SwCwwk) - [fcc](https://passist.org/siteswap/fcc?jugglers=4&hands=Ar-Bl-Cr-Dl-Al-Br-Cl-Dr)
  - [ecd](https://passist.org/siteswap/ecd?jugglers=4&hands=Ar-Bl-Cr-Dl-Al-Br-Cl-Dr) - pps variation (**TO-TRY**)

## 5 jugglers

See more info on stars and feasts with 5 jugglers in [this IJA article](https://www.juggle.org/five-person-feasts-and-stars/), by Aidan Burns.

- **Star (5 x 3 = 15 clubs)**
  - Start right‑handed, everyone holding 3 clubs (1|2).
  - Pass to the person two to your right (or two to your left if doing a left-handed pass).
  - Start with 4‑count. 3-count Star is very nice!
- **3‑count Feast (Boston circle)**
  - Pass to everyone in turn, including yourself (clock-wise)! All passes start right‑handed, then become left‑handed, etc.
  - Hand‑feast (nice variation, feels like Jim's).
  - Self-less feast variation!
- **5‑count Star with doubles (16 clubs)**
  - Pentagram positioning, each person passes 5‑count.
  - Double crossing passes for all.
  - 16 clubs (one person holds 4 clubs and starts throwing in the 1st beat).
  - In each beat a different person throws a crossing double (5 beats in total).
  - Pass to the person two to your right.

## Manipulation patterns {-#manipulation-patterns}

Intercepts (I), substitutions (S), carries (C), and so on...

### 3 jugglers {-}

- 4-count Roundabouts
  - [Mini Chopabout No. 1 - Simon](https://www.instagram.com/reel/C_zrJCfs27c/?igsh=amhvbzR3aTh3MnEw)
  - [Chopabout](https://fb.watch/m2ad3stFHq/)
  - [Slapabout](https://youtu.be/hQUMouImUaI)
  - [Ronjabout](https://passing.zone/ronjabout/)
  - Jim's 4-count Roundabout
  - Pop-about
    - M (2 clubs): C (to B) + S (to B), get the pop => A
    - A (2 clubs): 333p(gets substituted)333 => B
    - B (3 clubs): p333p33pop => M
- 3-count Roundabouts
  - [3-count Roundabout (Nickie's version)](https://passing.zone/nickis-3-count-roundabout/)
  - [Catch the carrot](https://passing.zone/catch-the-carrot/) - based on Jim's 3-count
- PPS Roundabouts
  - [Phoenician Waltz](https://passing.zone/phoenician-waltz/)
  - [MinuEd](https://passing.zone/minued/)
  - [Dolby 5.1](https://passing.zone/dolby-5-1-mit-einzel-und-doppelganger/) (5-count based)
  - [ChampV](https://passing.zone/champ-v/) (ppsps, all chops thrown from the same side - north wall pattern)
- Why-not Abouts
  - [What's that about (2014)](https://www.instagram.com/reel/Cm8Cam2u3tz/) - 4 gets intercepted
  - [Australian version](https://passing.zone/why-not-about) - [notation](https://photos.app.goo.gl/85EC5X2tkbCuZkAL9) - a pass gets intercepted
- [Shorty](https://passing.zone/shorty/)

### 4+ jugglers {-}

- Scrambled-V
  - [Variations](https://passing.zone/27-scrambleds/): 3,B,Toast,Zig-Zag
  - Scrambled-3V combo: 2 manipulators
  - **Kennedy**: 4-count Roundabout + 2 manipulators, [helicopter version](https://passing.zone/kennedy-helicopter-version/)
  - **Ambled-V**: +1 club, double passes
- [Cambled-V](https://passing.zone/cambled-v/)
  - Ambled-V variation
  - All start right-handed at the same time!
  - Feeder passes left-handed!
  - All passes are crossed!

## Minis {-}

### Clubs {-}

Mostly **side-by-side**

#### 3 clubs {-}

- 3p0 (cascade in-hands or out-hands)
- 2p1 (cascade-ish, in-hand to out-hand)

#### 4 clubs {-}

- 42p11p  
  - '4' are all 'alone' (one in each juggler's hand)
  - 2p: get it up in the air and leave it to fall
  - 1p: give it to the hand of the other juggler that does a '4'
  - Variation: change the roles of the two hands in each juggler and 2p becomes a front plane flat quick throw
- 2p3p12  
  - '2p' is the same club and goes up and down
  - '3p' can be a front flat throw

#### 5 clubs {-}

- [413p2](https://www.instagram.com/p/BsHEZpyA8Ii/?utm_source=ig_web_copy_link)  
3p: front half flat from outside hand to inside hand of the other juggler,
can be chest tipping (filmed with Doreen)
- [332p2](https://www.instagram.com/p/BsKwDn7gMFs/?utm_source=ig_web_copy_link)  
Second 3 as chest tip, 2p as 'reverse' chest tip, 2 reverse active high catch
(filmed with Doreen)

### Balls {-}

Mostly **face-to-face**

#### 3 Balls {-}

- 1p (|| vs x)
- 311p (|| vs x)
  - [3 person version](https://youtu.be/GC_fLpkLye8?t=68) - always straight passes to the person in your left
- 1.5p12 (423)
- 311p1 (||)

#### 4 Balls {-}

- 311p3p (||)
- 312 variations: 3p12,31p2,312p,...,3p1p2p!!!

#### 5 Balls {-}

- [Partner Arm Weave Columns](https://youtu.be/KVxZmKU21W0?t=116)

